approval_policy = "never"
#sandbox_mode = "workspace-write"
sandbox_mode = "danger-full-access"


[model_providers.myollama]
name = "Ollama"
base_url = "http://192.168.64.1:11434/v1"
wire_api = "responses"

[profiles.gpt-oss]
model_provider = "myollama"
model = "gpt-oss:20b"
model_context_window = 131072
model_catalog_json = "~/.codex/local_models.json"

[profiles.gemma]
model_provider = "myollama"
model = "gemma4:26b-a4b-it-q4_K_M"
model_context_window = 131072

[profiles.qwen]
model_provider = "myollama"
model = "qwen3.5:35b-a3b-coding-nvfp4"
model_context_window = 131072

[projects."/workdir"]
trust_level = "trusted"